swagger: "2.0"
info:
  version: 1.0.0
  title: Jotihunt
  description: De jotihunt is een initiatief van Scouting Gelderland. De Jotihunt site/app zijn origineel gemaakt door de Scouting Roothaangroep en worden beschikbaar gesteld aan alle deelnemende groepen.
  termsOfService: https://jotihunt-roothaan.herokuapp.com/
  contact:
    name: Jasper Roel
    email: jasperroel@gmail.com
    url: http://www.jasperroel.nl
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
#host: jotihunt-roothaan.herokuapp.com
host: roothaan-jotihunt-beta.herokuapp.com
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apiAuthentication:
    type: apiKey
    in: header
    name: authenticationToken
    description: |
      This is the token you received from the /api/auth endpoint.
      Example format would be:
      
      `authenticationToken: 7yTT7vpOcp4GHWgxR7pLSf08viO5JHFWRKm+eq6MfHiO5tQOin/BYQ==`

security:
  - apiAuthentication: [] 
    
paths:
  /auth:
    post:
      security : []
      description: |
        Login and receive a token for the rest of your authenicated interaction
      operationId: loginViaApi
      responses:
        200:
          description: |
            Login token <br />
            <code>{<br />
            &nbsp;&nbsp;&nbsp;&nbsp;"token": "7yTT7vpOcp4GHWgxR7pLSf08viO5JHFWRKm+eq6MfHiO5tQOin/BYQ=="<br />
            }</code>
          schema: 
            type: array
      parameters:
        - name: AuthenticationUsername
          in: header
          description: Your username
          required: true
          type: string
          format: string
        - name: AuthenticationPassword
          in: header
          description: Your username
          required: true
          type: string
          format: password
  /events:
    get:
      description: |
        Returns all events you can publicly see
      operationId: getEvents
      responses:
        200:
          description: Event array
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Sets your event for this session
      operationId: setEvent
      parameters:
        - name: eventId
          in: body
          description: Pet to add to the store
          required: true
          schema:
            $ref: '#/definitions/NewPet'
      responses:
        200:
          description: pet response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /events/{id}:
    get:
      description: Returns an event based on a single ID
      operationId: find event by id
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: pet response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single pet based on the ID supplied
      operationId: deletePet
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: pet deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Pet:
    allOf:
      - $ref: '#/definitions/NewPet'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewPet:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string